# Waypoints to KML

In [18]:
# imports
from importlib import reload
import numpy as np
import pandas

from remote_sensing import kml as rs_kml

# Load up

In [6]:
wp = pandas.read_table('HS_flightplan1_110m_sim_worked.waypoints', skiprows=1,
                      names=['sequence', 'current_waypoint', 'coordinate_frame', 'command', 'param1', 'param2',
                             'param3','param4','latitude','longitude','altitude','autocontinue'])
wp.head()

,sequence,current_waypoint,coordinate_frame,command,param1,param2,param3,param4,latitude,longitude,altitude,autocontinue
0,0,1,0,16,0.00000,0.0,0.0,0.0,36.905396,-121.841426,14.94,1
1,1,0,3,22,0.00000,0.0,0.0,0.0,0.000000,0.000000,30.00,1
2,2,0,3,82,0.00000,0.0,0.0,0.0,36.907459,-121.849779,110.00,1
3,3,0,3,82,0.00000,0.0,0.0,0.0,36.907216,-121.849638,110.00,1
4,4,0,0,206,68.49378,0.0,1.0,0.0,0.000000,0.000000,0.00,1

# Strip out the flight lines

In [13]:
good_rows = np.zeros(len(wp), dtype=bool)
for ss, row in wp.iterrows():
    # 206
    if row.command == 206:
        good_rows[ss-1] = True
        sv_last = ss-1
# Trim the last one
good_rows[sv_last] = False

In [14]:
specim_wp = wp[good_rows].copy()
specim_wp.head()

,sequence,current_waypoint,coordinate_frame,command,param1,param2,param3,param4,latitude,longitude,altitude,autocontinue
3,3,0,3,82,0.0,0.0,0.0,0.0,36.907216,-121.849638,110.0,1
5,5,0,3,16,0.0,0.0,0.0,0.0,36.895232,-121.842726,110.0,1
9,9,0,3,82,0.0,0.0,0.0,0.0,36.894931,-121.843610,110.0,1
11,11,0,3,16,0.0,0.0,0.0,0.0,36.906970,-121.850547,110.0,1
15,15,0,3,82,0.0,0.0,0.0,0.0,36.906726,-121.851469,110.0,1

In [15]:
len(specim_wp)

20

# Generate flight lines

# KML

In [19]:
reload(rs_kml)
rs_kml.scatter_to_kml_advanced(specim_wp.longitude.values, 
                               specim_wp.latitude.values)

Saved output.kml